
module omnicxy
{
module proto
{
module interop
{
module a
{
  interface reflect
  {
    // returns x
    any f(in long step, in any x);
  };
  interface server
  {
    void run(in reflect f);
  };

  struct S
  {
    long x_;
    string y_;
  };

  typedef S ThreeSs[3];

  
  union U1 switch(short)
  {
  case 1: long x_;
  default: string y_;
  };

  enum E
  {
    EV1,
    EV2
  };

  union U2 switch(E)
  {
  case EV1: long x_;
  case EV2: string y_;
  };
  
  //recursive
  struct Tree;
  typedef sequence<Tree> Branches;
  struct Tree
  {
    string name_;
    Branches children_;
  };

  exception X
  {
    string message_;
  };
  
};
};
};
};
