module omnicxy
{
module proto
{
module interop
{
module a
{
  struct S
  {
    long x_;
    string y_;
  };
  
  interface reflect
  {
    // returns x
    any f(in long step, in any x);
  };
  interface server
  {
    void run(in reflect f);
  };
};
};
};
};
