#ifndef HCP_TAGS_LOOKUP
#define HCP_TAGS_LOOKUP

#include <hcp/tags/NamespaceName.idl>
#include <hcp/tags/FoundIn.idl>
#include <hcp/tags/UnqualifiedSymbol.idl>

module hcp
{
  module tags
  {
    interface Lookup
    {
      typedef sequence<NamespaceName> NamespaceNames;
      FoundIn lookupSymbol(in NamespaceNames fromScope,
                           in NamespaceNames symbolScope,
                           in UnqualifiedSymbol symbol);
    };
  };
};

#endif
