const string p11_Z = "z";
const short p11_Q = 10;

enum X {
  A, B, C
};
union U1 switch(X) {
  case A: long a_;
  case C: float c_;
};

module p11
{
  interface F
  {
    U1 f1(in U1 a);

    enum Y{
      U, V
    };
    union U2 switch(Y) {
    case U: string u_;
    case V: short v_;
    };
  };
};
