module p13
{
  union U1 switch(short) {
  case 1: long a_;
  case 2: float c_;
  default: string x_;
  };

  interface F
  {
    void f1(in U1 a);

    union U2 switch(long) {
    case 3: string c3;
    default: long d_;
    };
  };
};
