module p20
{
  struct A
  {
    short a_;
  };
  struct B
  {
    any b_;
  };
  typedef sequence<short> SS;
  
  interface F{
    // returns x
    any f1(in any x);

    // returns x
    short f2(in short x);

    // returns x
    B f3(in B x);
  };
};
