#!/usr/bin/env python

import sys
import os.path

import json
def toJson(x):
    return json.dumps(x,sort_keys=True,indent=4,separators=(',',': '),
                      cls=json.JSONEncoder)
def fromJson(x):
    return json.loads(x)

result={}
for f in sys.argv[1:]:
    try:
        result.update(fromJson(file(f).read()))
    except Exception,e:
        raise Exception('failed to merge tags because failed to read tags from file {f!r} because {e}'.format(vars()))
    pass
print toJson(result)
