#!/bin/sh
#
# Wrapper to create Odin cache after first checking for necessary
# environment.
#
d=`dirname $0`

clone=$0

if [ -z "$NO_XERCES" ]
then
   if [ -z "$XERCES_HOME" ]
   then
      XERCES_HOME=/usr
   fi
   if [ ! -r $XERCES_HOME/include/xercesc ]
   then
      echo "Error: $XERCES_HOME/include/xercesc does not exist" >&2
      echo "Info: set XERCES_HOME so that \$XERCES_HOME/include/xercesc exists" >&2
      exit 1
   fi
   xerces_inc="$XERCES_HOME/include"
   xerces_lib="$XERCES_HOME/lib"
   xerces_ignore="|$xerces_inc"
   clone="XERCES_HOME=$XERCES_HOME $clone"
else
   clone="NO_XERCES=1 $clone"
fi

if [ -z "$NO_QT" ]
then
   if [ ! -r $QT_HOME/include ]
   then
      echo "Error: $QT_HOME/include does not exist" >&2
      echo "set QT_HOME so that \$QT_HOME/include exists" >&2
      echo "set NO_QT to go without Qt" >&2
      exit 1
   else
      qt_inc="$QT_HOME/include"
      qt_lib="$QT_HOME/lib"
      qt_ignore="|$QT_HOME/include"
      clone="QT_HOME=$QT_HOME $clone"
   fi
else
   clone="NO_QT=1 $clone"
fi

if [ -z "$ODIN" ]
then
   echo "Error: \$ODIN not set" >&2
   echo "Info: set \$ODIN to desired cache location" >&2
   exit 1
fi

x=`which odin`
if [ $? != 0 ]
then
   echo "Error: odin not on path" >&2
   echo "Info: ensure odin is on \$PATH" >&2
   exit 1
fi

ODINPATH=$d/../bal/odin/pkg \
ODIN_CXX=g++ \
ODIN_CXX_FLAGS=-g \
ODIN_CXX_PATH=/usr/bin \
ODIN_CXX_AR_PATH=/usr/bin \
ODIN_QT_MOC_PATH=$QT_HOME/bin \
ODIN_QT_MOC=moc \
ODIN_QTDIR=$QT_HOME \
ODIN_LIB_SP="$XERCES_HOME/lib $qt_lib /lib /usr/lib" \
ODIN_CXX_LD_LIBRARY_PATH="$xerces_lib $qt_lib" \
ODIN_LD_LIBRARY_PATH="$xerces_lib $qt_lib" \
ODIN_CXX_I="$xerces_inc $qt_inc" \
ODIN_IGNORE="/dev/null${xerces_ignore}${qt_ignore}" \
odin -R </dev/null

(
  echo "# cache can be recreated with:" &&
  echo "$clone"
) > $ODIN/README
