#!/bin/sh
#
# Wrapper to create Odin cache after first checking for necessary
# environment.
#
d=`dirname $0`

clone=$0

if [ -z "$XERCES_HOME" ]
then
   XERCES_HOME=/usr
fi
if [ ! -r $XERCES_HOME/include/xercesc ]
then
   echo "Error: $XERCES_HOME/include/xercesc does not exist" >&2
   echo "Info: set XERCES_HOME so that \$XERCES_HOME/include/xercesc exists" >&2
   exit 1
fi
clone="XERCES_HOME=$XERCES_HOME $clone"

if [ -z "$MINGW" ]
then
   MINGW=/cygdrive/c/MinGW-3.1.0-1
fi
if [ ! -x "$MINGW/bin/g++" ]
then
   echo "Error: $MINGW/bin/g++ not found" >&2
   echo "Info: set MINGW so that \$MINGW/bin/g++ locates MinGW g++" >&2
   return 1
fi
clone="MINGW=$MINGW $clone"

if [ -z "$NO_QT" ]
then
   if [ -z "$QT_HOME" ]
   then
      QT_HOME=/cygdrive/c/Qt/qt-2.3.2
   fi
   if [ ! -r $QT_HOME/include ]
   then
      echo "Error: $QT_HOME/include does not exist" >&2
      echo "set QT_HOME so that \$QT_HOME/include exists" >&2
      echo "set NO_QT to go without Qt" >&2
      exit 1
   else
      qt_inc="$QT_HOME/include"
      qt_lib="$QT_HOME/lib"
      qt_ignore="|$QT_HOME/include"
      clone="QT_HOME=$QT_HOME $clone"
   fi
else
   clone="NO_QT=1 $clone"
fi

if [ -z "$NO_FLTK" ]
then
   if [ ! -r "$FLTK_HOME/include/fltk-1.1/Fl/Fl.h" ]
   then
      echo "Error: $FLTK_HOME/include/fltk-1.1/Fl/Fl.h does not exist" >&2
      echo "set FLTK_HOME so that \$FLTK_HOME/include/fltk-1.1/Fl/Fl.h exists" >&2
      echo "set NO_FLTK to go without fltk" >&2
      exit 1
   else
      fltk_inc="$FLTK_HOME/include/fltk-1.1"
      fltk_lib="$FLTK_HOME/lib/fltk-1.1"
      fltk_ignore="|$FLTK_HOME/include/fltk-1.1"
      clone="FLTK_HOME=$FLTK_HOME $clone"
   fi
else
   clone="NO_FLTK=1 $clone"
fi

if [ -z "$ODIN" ]
then
   echo "Error: \$ODIN not set" >&2
   echo "Info: set \$ODIN to desired cache location" >&2
   return 1
fi

x=`which odin`
if [ $? != 0 ]
then
   echo "Error: odin not on path" >&2
   echo "Info: ensure odin is on \$PATH" >&2
   return 1
fi

XERCES_C_2_7_0_CXX_FLAGS="-DNDEBUG -DPROJ_XMLPARSER -DPROJ_XMLUTIL -DPROJ_PARSERS -DPROJ_SAX4C -DPROJ_SAX2 -DPROJ_DOM -DPROJ_DEPRECATED_DOM -DPROJ_VALIDATORS -DXML_USE_WIN32_TRANSCODER -DXML_USE_INMEM_MESSAGELOADER"
ODINPATH=$d/../bal/odin/pkg \
ODIN_CXX_PATH=$d/../bal/odin/util:$MINGW/bin \
ODIN_CXX=mingw-g++ \
ODIN_CXX_FLAGS="-g -DXJU_WIN32_MINGW $XERCES_C_2_7_0_CXX_FLAGS" \
ODIN_CXX_AR_PATH=/usr/bin \
ODIN_QT_MOC_PATH=$d/../bal/odin/util:$QT_HOME/bin \
ODIN_QT_MOC=qt-moc-windows \
ODIN_QTDIR=$QT_HOME \
ODIN_LIB_SP="$XERCES_HOME/lib $qt_lib $fltk_lib /lib /usr/lib" \
ODIN_CXX_LD_LIBRARY_PATH="$XERCES_HOME/lib $qt_lib $fltk_lib" \
ODIN_LD_LIBRARY_PATH="$XERCES_HOME/lib $qt_lib $fltk_lib" \
ODIN_CXX_I="$XERCES_HOME/include $qt_inc $fltk_inc" \
ODIN_IGNORE="${XERCES_HOME}${qt_ignore}|${fltk_ignore}" \
odin -R </dev/null

(
  echo "# cache can be recreated with:" &&
  echo "$clone"
) > $ODIN/README
