// Copyright (c) 2019 Trevor Taylor
//
// Permission to use, copy, modify, distribute and sell this software
// and its documentation for any purpose is hereby granted without fee,
// provided that the above copyright notice appear in all.
// Trevor Taylor makes no representations about the suitability of this
// software for any purpose.  It is provided "as is" without express or
// implied warranty.
//
#ifndef XJU_LINUX_WTMP_EVENT_IDL
#define XJU_LINUX_WTMP_EVENT_IDL

#include <cxy/UnixTimeMilli.idl>
#include <xju/linux/wtmp/EventType_.idl>
#include <xju/linux/wtmp/UserLoggedIn.idl>
#include <xju/linux/wtmp/UserLoggedOut.idl>

module xju
{
  module linux
  {
    module wtmp
    {
      union Event switch(EventType_)
      {
      case USER_LOGGED_IN: UserLoggedIn userLoggedIn_;
      case USER_LOGGED_OUT: UserLoggedOut userLoggedOut_;
      };
    };
  };
};

#endif
