// Copyright (c) 2019 Trevor Taylor
//
// Permission to use, copy, modify, distribute and sell this software
// and its documentation for any purpose is hereby granted without fee,
// provided that the above copyright notice appear in all.
// Trevor Taylor makes no representations about the suitability of this
// software for any purpose.  It is provided "as is" without express or
// implied warranty.
//
#include <cxy/UnixTimeMilli.idl>

module xju
{
  module linux
  {
    module wtmp
    {
      module event
      {
        struct UserLoggedIn
        {
          string username_;
          string from_;
          ::cxy::UnixTimeMilli at_;
        };

        struct UserLoggedOut
        {
          UserLoggedIn who_;
          ::cxy::UnixTimeMilli at_;
        };

        enum Type {
          USER_LOGGED_IN,
          USER_LOGGED_OUT
        };

        union Event_ switch(Type)
        {
        case USER_LOGGED_IN: UserLoggedIn userLoggedIn_;
        case USER_LOGGED_OUT: UserLoggedOut userLoggedOut_;
        };
      };
    };
  };
};
