#!/bin/env python
# coding: utf-8
#
# Copyright (c) 2018 Trevor Taylor
# 
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that all
# copyright notices and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

import sys

template='''\
//generated by xju/test/CallToPn.py

#include <xju/test/CallTo.hh>

namespace xju
{{
namespace test
{{

template<class T,class U{pClasses}>
class CallToV{nParams} : public CallToVoid
{{
public:
  explicit CallToV{nParams}(
    T& x,void 
    (U::*f)({fParams}){params})
      : x_(x),
        f_(f){paramInits}
  {{
  }}
  T& x_;
  void (U::* const f_)({fParams});{paramMembers}
}};


template<class T,class U,class R{pClasses}>
class CallToR{nParams} : public CallToR<R>
{{
public:
  explicit CallToR{nParams}(
    T& x,
    R (U::*f)({fParams}){params})
      : x_(x),
        f_(f){paramInits}
  {{
  }}
  T& x_;
  R (U::* const f_)({fParams});{paramMembers}
}};

template<class T,class U{pClasses}>
class CallToVc{nParams} : public CallToVoid
{{
public:
  explicit CallToVc{nParams}(
    T const& x,void 
    (U::*f)({fParams}) const{params})
      : x_(x),
        f_(f){paramInits}
  {{
  }}
  T const& x_;
  void (U::* const f_)({fParams}) const;{paramMembers}
}};


template<class T,class U,class R{pClasses}>
class CallToRc{nParams} : public CallToR<R>
{{
public:
  explicit CallToRc{nParams}(
    T const& x,
    R (U::*f)({fParams}) const{params})
      : x_(x),
        f_(f){paramInits}
  {{
  }}
  T const& x_;
  R (U::* const f_)({fParams}) const;{paramMembers}
}};

}}
}}
'''

nParams=int(sys.argv[1])
pClasses=''.join([',class P{n}'.format(**vars())
                  for n in range(1,nParams+1)])
fParams=','.join(['P{n}'.format(**vars())
                  for n in range(1,nParams+1)])
params=  ''.join([',\n    P{n} const& p{n}'.format(**vars())
                  for n in range(1,nParams+1)])
paramInits=''.join([',\n        p{n}_(p{n})'.format(**vars())
                    for n in range(1,nParams+1)])
paramMembers=''.join(['\n  P{n} const& p{n}_;'.format(**vars())
                      for n in range(1,nParams+1)])

print(template.format(**vars()))
