// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "BttLayout.h"

BttLayout::BttLayout() {
  fltk::Window* w;
   {fltk::Window* o = window = new fltk::Window(300, 195, "BTT");
    w = o;
    o->set_vertical();
    o->shortcut(0xff1b);
    o->user_data((void*)(this));
    o->begin();
     {fltk::MenuBar* o = menubar = new fltk::MenuBar(0, 0, 300, 20);
      o->shortcut(0xffe9);
      o->begin();
       {fltk::ItemGroup* o = taskMenu = new fltk::ItemGroup("Task");
        o->begin();
         {fltk::Item* o = newTask = new fltk::Item("&New Task before Selected Task");
          o->shortcut(0x4006e);
        }
         {fltk::Item* o = newTaskAtEnd = new fltk::Item("New Task at &End");
          o->shortcut(0x40065);
        }
         {fltk::Item* o = editSelected = new fltk::Item("&Selected Task...");
          o->shortcut(0xff0d);
        }
        o->end();
      }
       {fltk::ItemGroup* o = editMenu = new fltk::ItemGroup("Edit");
        o->begin();
         {fltk::Item* o = undo = new fltk::Item("&Undo");
          o->shortcut(0x4007a);
        }
         {fltk::Item* o = redo = new fltk::Item("&Redo");
          o->shortcut(0x40079);
        }
        o->end();
      }
       {fltk::ItemGroup* o = reportMenu = new fltk::ItemGroup("Report");
        o->begin();
        timeSheet = new fltk::Item("Time Sheet");
        rollupTimeSheet = new fltk::Item("Rollup Timsheet");
        o->end();
      }
      o->end();
    }
    currentTask = new fltk::Output(0, 20, 300, 25);
     {fltk::Browser* o = tasks = new fltk::Browser(0, 45, 300, 150);
      fltk::Group::current()->resizable(o);
      fltk::Group::current()->resizable(o);
    }
     {fltk::PopupMenu* o = startMenu = new fltk::PopupMenu(0, 45, 300, 150, "Start");
      o->hide();
      ((fltk::Window*)(o->parent()))->hotspot(o);
      o->begin();
      startNow = new fltk::Item("Now");
      startMinus5 = new fltk::Item("5 Minutes Ago");
      startMinus15 = new fltk::Item("15 Minutes Ago");
      startMinus30 = new fltk::Item("30 Minutes Ago");
      startMinus45 = new fltk::Item("45 Minutes Ago");
      startMinus60 = new fltk::Item("1 Hour Ago");
      startMinus90 = new fltk::Item("90 Minutes Ago");
      startMinus120 = new fltk::Item("2 Hours Ago");
      startAt = new fltk::Item("At...");
      o->end();
    }
    o->end();
  }
}
