// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef BttLayout_h
#define BttLayout_h
#include <fltk/Window.h>
#include <fltk/MenuBar.h>
#include <fltk/ItemGroup.h>
#include <fltk/Item.h>
#include <fltk/Output.h>
#include <fltk/Browser.h>
#include <fltk/PopupMenu.h>

class BttLayout  {
public:
  BttLayout();
  fltk::Window *window;
    fltk::MenuBar *menubar;
      fltk::ItemGroup *taskMenu;
        fltk::Item *newTask;
        fltk::Item *newTaskAtEnd;
        fltk::Item *editSelected;
      fltk::ItemGroup *editMenu;
        fltk::Item *undo;
        fltk::Item *redo;
      fltk::ItemGroup *reportMenu;
        fltk::Item *timeSheet;
        fltk::Item *rollupTimeSheet;
    fltk::Output *currentTask;
    fltk::Browser *tasks;
    fltk::PopupMenu *startMenu;
      fltk::Item *startNow;
      fltk::Item *startMinus5;
      fltk::Item *startMinus15;
      fltk::Item *startMinus30;
      fltk::Item *startMinus45;
      fltk::Item *startMinus60;
      fltk::Item *startMinus90;
      fltk::Item *startMinus120;
      fltk::Item *startAt;
};
#endif
