// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef BttLayout_h
#define BttLayout_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Browser.H>

class BttLayout {
public:
  BttLayout();
  Fl_Window *window;
  Fl_Menu_Bar *menubar;
  static Fl_Menu_Item menu_menubar[];
  static Fl_Menu_Item *taskMenu;
  static Fl_Menu_Item *newTask;
  static Fl_Menu_Item *newTaskAtEnd;
  static Fl_Menu_Item *editSelected;
  static Fl_Menu_Item *editMenu;
  static Fl_Menu_Item *undo;
  static Fl_Menu_Item *redo;
  static Fl_Menu_Item *reportMenu;
  static Fl_Menu_Item *timeSheet;
  static Fl_Menu_Item *rollupTimeSheet;
  static Fl_Menu_Item *startMenu;
  static Fl_Menu_Item *startNow;
  Fl_Output *currentTask;
  Fl_Browser *tasks;
};
#endif
