// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "p10.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



p10::F_ptr p10::F_Helper::_nil() {
  return ::p10::F::_nil();
}

::CORBA::Boolean p10::F_Helper::is_nil(::p10::F_ptr p) {
  return ::CORBA::is_nil(p);

}

void p10::F_Helper::release(::p10::F_ptr p) {
  ::CORBA::release(p);
}

void p10::F_Helper::marshalObjRef(::p10::F_ptr obj, cdrStream& s) {
  ::p10::F::_marshalObjRef(obj, s);
}

p10::F_ptr p10::F_Helper::unmarshalObjRef(cdrStream& s) {
  return ::p10::F::_unmarshalObjRef(s);
}

void p10::F_Helper::duplicate(::p10::F_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

p10::F_ptr
p10::F::_duplicate(::p10::F_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

p10::F_ptr
p10::F::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


p10::F_ptr
p10::F::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

p10::F_ptr
p10::F::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_F _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_F* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_F;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* p10::F::_PD_repoId = "IDL:p10/F:1.0";


p10::_objref_F::~_objref_F() {
  
}


p10::_objref_F::_objref_F(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::p10::F::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
p10::_objref_F::_ptrToObjRef(const char* id)
{
  if (id == ::p10::F::_PD_repoId)
    return (::p10::F_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::p10::F::_PD_repoId))
    return (::p10::F_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for p10::F::f1

// Proxy call descriptor class. Mangled signature:
//  void_i_cp10_mEN
class _0RL_cd_c6f716139037bfb6_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_c6f716139037bfb6_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  p10::EN arg_0;
};

void _0RL_cd_c6f716139037bfb6_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_c6f716139037bfb6_00000000::unmarshalArguments(cdrStream& _n)
{
  (p10::EN&)arg_0 <<= _n;

}

const char* const _0RL_cd_c6f716139037bfb6_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_c6f716139037bfb6_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_c6f716139037bfb6_00000000* tcd = (_0RL_cd_c6f716139037bfb6_00000000*)cd;
  p10::_impl_F* impl = (p10::_impl_F*) svnt->_ptrToInterface(p10::F::_PD_repoId);
  impl->f1(tcd->arg_0);


}

void p10::_objref_F::f1(::p10::EN a)
{
  _0RL_cd_c6f716139037bfb6_00000000 _call_desc(_0RL_lcfn_c6f716139037bfb6_10000000, "f1", 3);
  _call_desc.arg_0 = a;

  _invoke(_call_desc);



}

p10::_pof_F::~_pof_F() {}


omniObjRef*
p10::_pof_F::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::p10::_objref_F(ior, id);
}


::CORBA::Boolean
p10::_pof_F::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::p10::F::_PD_repoId))
    return 1;
  
  return 0;
}

const p10::_pof_F _the_pof_p10_mF;

p10::_impl_F::~_impl_F() {}


::CORBA::Boolean
p10::_impl_F::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "f1")) {

    _0RL_cd_c6f716139037bfb6_00000000 _call_desc(_0RL_lcfn_c6f716139037bfb6_10000000, "f1", 3, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
p10::_impl_F::_ptrToInterface(const char* id)
{
  if (id == ::p10::F::_PD_repoId)
    return (::p10::_impl_F*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::p10::F::_PD_repoId))
    return (::p10::_impl_F*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
p10::_impl_F::_mostDerivedRepoId()
{
  return ::p10::F::_PD_repoId;
}

POA_p10::F::~F() {}

