// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __p11_hh__
#define __p11_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_p11
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_p11
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_p11
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_GLOBAL_VAR _core_attr const char * p11_Z;

_CORBA_GLOBAL_VARINT const ::CORBA::Short p11_Q _init_in_decl_( = 10 );

enum X { A, B, C /*, __max_X=0xffffffff */ };
typedef X& X_out;

class U1 {
public:

  typedef _CORBA_ConstrType_Fix_Var<U1> _var_type;

  

  U1(): _pd__initialised(0) {
    _default();


  }
  
  U1(const U1& _value) : _pd__initialised(0) {
    if ((_pd__default = _value._pd__default)) {
      
    }
    else {
      switch(_value._pd__d) {
        case A: a_(_value.a_()); break;

        case C: c_(_value.c_()); break;

          default: break;

    
      }
    }
    _pd__d = _value._pd__d;


    _pd__initialised = _value._pd__initialised;
  }

  ~U1() {
    _release_member();
  }

  U1& operator=(const U1& _value) {
    if ((_pd__default = _value._pd__default)) {
      
    }
    else {
      switch(_value._pd__d) {
        case A: a_(_value.a_()); break;

        case C: c_(_value.c_()); break;

          default: break;

    
      }
    }
    _pd__d = _value._pd__d;


    _pd__initialised = _value._pd__initialised;
    return *this;
  }

  X _d() const { return _pd__d;}
  void _d(X _value){
    // illegal to set discriminator before making a member active
    if (!_pd__initialised)
      OMNIORB_THROW(BAD_PARAM,_OMNI_NS(BAD_PARAM_InvalidUnionDiscValue),::CORBA::COMPLETED_NO);

    if (_value == _pd__d) return; // no change

    switch (_pd__d){
      case A: goto fail;
      case C: goto fail;
      default:
      switch (_value){
        case A: goto fail;
        case C: goto fail;
        default: _pd__d = _value; return;
      }

    };
    

    fail:
    OMNIORB_THROW(BAD_PARAM,_OMNI_NS(BAD_PARAM_InvalidUnionDiscValue),::CORBA::COMPLETED_NO);



  }

  void _default()
  {
    _pd__initialised = 1;
    _pd__d = B;
    _pd__default = 1;
  }



  ::CORBA::Long a_ () const { return _pd_a_; }
  void a_ (::CORBA::Long  _value) {
    _release_member();
    _pd__initialised = 1;
    _pd__d = A;
    _pd__default = 0;
    _pd_a_ = _value;
  }

  ::CORBA::Float c_ () const { return _pd_c_; }
  void c_ (::CORBA::Float  _value) {
    _release_member();
    _pd__initialised = 1;
    _pd__d = C;
    _pd__default = 0;
    _pd_c_ = _value;
  }


  
  void operator>>= (cdrStream&) const;
  void operator<<= (cdrStream&);

private:
  X _pd__d;
  _CORBA_Boolean _pd__default;
  _CORBA_Boolean _pd__initialised;

  union {
    ::CORBA::Long _pd_a_;
#ifndef USING_PROXY_FLOAT
    ::CORBA::Float _pd_c_;
#else
    ::CORBA::Float* _pd_c_;
#endif

  };
  inline void _release_member () {
  }

};

typedef U1::_var_type U1_var;

typedef U1& U1_out;

_CORBA_MODULE p11

_CORBA_MODULE_BEG

#ifndef __p11_mF__
#define __p11_mF__
  class F;
  class _objref_F;
  class _impl_F;
  
  typedef _objref_F* F_ptr;
  typedef F_ptr FRef;

  class F_Helper {
  public:
    typedef F_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_F, F_Helper> F_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_F,F_Helper > F_out;

#endif

  // interface F
  class F {
  public:
    // Declarations for this interface type.
    typedef F_ptr _ptr_type;
    typedef F_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_F :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void f1(const ::U1& a);

    // Constructors
    inline _objref_F()  { _PR_setobj(0); }  // nil
    _objref_F(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_F();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_F(const _objref_F&);
    _objref_F& operator = (const _objref_F&);
    // not implemented

    friend class F;
  };

  class _pof_F : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_F() : _OMNI_NS(proxyObjectFactory)(F::_PD_repoId) {}
    virtual ~_pof_F();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_F :
    public virtual omniServant
  {
  public:
    virtual ~_impl_F();

    virtual void f1(const ::U1& a) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_p11
_CORBA_MODULE_BEG

  class F :
    public virtual p11::_impl_F,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~F();

    inline ::p11::F_ptr _this() {
      return (::p11::F_ptr) _do_this(::p11::F::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_p11
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

inline void operator >>=(X _e, cdrStream& s) {
  ::operator>>=((::CORBA::ULong)_e, s);
}

inline void operator <<= (X& _e, cdrStream& s) {
  ::CORBA::ULong _0RL_e;
  ::operator<<=(_0RL_e,s);
  if (_0RL_e <= C) {
    _e = (X) _0RL_e;
  }
  else {
    OMNIORB_THROW(MARSHAL,_OMNI_NS(MARSHAL_InvalidEnumValue),
                  (::CORBA::CompletionStatus)s.completion());
  }
}



inline void
p11::F::_marshalObjRef(::p11::F_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_p11
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_p11
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_p11
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_p11
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_p11
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_p11
#endif

#endif  // __p11_hh__

