// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __p15_hh__
#define __p15_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_p15
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_p15
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_p15
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE p15

_CORBA_MODULE_BEG

#ifndef __p15_mAAA__
#define __p15_mAAA__
  class AAA;
  class _objref_AAA;
  class _impl_AAA;
  
  typedef _objref_AAA* AAA_ptr;
  typedef AAA_ptr AAARef;

  class AAA_Helper {
  public:
    typedef AAA_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_AAA, AAA_Helper> AAA_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_AAA,AAA_Helper > AAA_out;

#endif

  // interface AAA
  class AAA {
  public:
    // Declarations for this interface type.
    typedef AAA_ptr _ptr_type;
    typedef AAA_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_AAA :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Long f(::CORBA::Long x);

    // Constructors
    inline _objref_AAA()  { _PR_setobj(0); }  // nil
    _objref_AAA(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_AAA();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_AAA(const _objref_AAA&);
    _objref_AAA& operator = (const _objref_AAA&);
    // not implemented

    friend class AAA;
  };

  class _pof_AAA : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_AAA() : _OMNI_NS(proxyObjectFactory)(AAA::_PD_repoId) {}
    virtual ~_pof_AAA();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_AAA :
    public virtual omniServant
  {
  public:
    virtual ~_impl_AAA();

    virtual ::CORBA::Long f(::CORBA::Long x) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


#ifndef __p15_mBBB__
#define __p15_mBBB__
  class BBB;
  class _objref_BBB;
  class _impl_BBB;
  
  typedef _objref_BBB* BBB_ptr;
  typedef BBB_ptr BBBRef;

  class BBB_Helper {
  public:
    typedef BBB_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_BBB, BBB_Helper> BBB_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_BBB,BBB_Helper > BBB_out;

#endif

  // interface BBB
  class BBB {
  public:
    // Declarations for this interface type.
    typedef BBB_ptr _ptr_type;
    typedef BBB_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_BBB :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    AAA_ptr getA();

    // Constructors
    inline _objref_BBB()  { _PR_setobj(0); }  // nil
    _objref_BBB(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_BBB();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_BBB(const _objref_BBB&);
    _objref_BBB& operator = (const _objref_BBB&);
    // not implemented

    friend class BBB;
  };

  class _pof_BBB : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_BBB() : _OMNI_NS(proxyObjectFactory)(BBB::_PD_repoId) {}
    virtual ~_pof_BBB();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_BBB :
    public virtual omniServant
  {
  public:
    virtual ~_impl_BBB();

    virtual AAA_ptr getA() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_p15
_CORBA_MODULE_BEG

  class AAA :
    public virtual p15::_impl_AAA,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~AAA();

    inline ::p15::AAA_ptr _this() {
      return (::p15::AAA_ptr) _do_this(::p15::AAA::_PD_repoId);
    }
  };

  class BBB :
    public virtual p15::_impl_BBB,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~BBB();

    inline ::p15::BBB_ptr _this() {
      return (::p15::BBB_ptr) _do_this(::p15::BBB::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_p15
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
p15::AAA::_marshalObjRef(::p15::AAA_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
p15::BBB::_marshalObjRef(::p15::BBB_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_p15
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_p15
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_p15
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_p15
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_p15
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_p15
#endif

#endif  // __p15_hh__

