// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "p15.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



p15::AAA_ptr p15::AAA_Helper::_nil() {
  return ::p15::AAA::_nil();
}

::CORBA::Boolean p15::AAA_Helper::is_nil(::p15::AAA_ptr p) {
  return ::CORBA::is_nil(p);

}

void p15::AAA_Helper::release(::p15::AAA_ptr p) {
  ::CORBA::release(p);
}

void p15::AAA_Helper::marshalObjRef(::p15::AAA_ptr obj, cdrStream& s) {
  ::p15::AAA::_marshalObjRef(obj, s);
}

p15::AAA_ptr p15::AAA_Helper::unmarshalObjRef(cdrStream& s) {
  return ::p15::AAA::_unmarshalObjRef(s);
}

void p15::AAA_Helper::duplicate(::p15::AAA_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

p15::AAA_ptr
p15::AAA::_duplicate(::p15::AAA_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

p15::AAA_ptr
p15::AAA::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


p15::AAA_ptr
p15::AAA::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

p15::AAA_ptr
p15::AAA::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_AAA _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_AAA* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_AAA;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* p15::AAA::_PD_repoId = "IDL:p15/AAA:1.0";


p15::_objref_AAA::~_objref_AAA() {}



p15::_objref_AAA::_objref_AAA(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::p15::AAA::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
p15::_objref_AAA::_ptrToObjRef(const char* id)
{
  if (id == ::p15::AAA::_PD_repoId)
    return (::p15::AAA_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::p15::AAA::_PD_repoId))
    return (::p15::AAA_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for p15::AAA::f

// Proxy call descriptor class. Mangled signature:
//  _clong_i_clong
class _0RL_cd_c06bfb5befae7381_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_c06bfb5befae7381_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Long result;
};

void _0RL_cd_c06bfb5befae7381_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_c06bfb5befae7381_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

void _0RL_cd_c06bfb5befae7381_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_c06bfb5befae7381_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_c06bfb5befae7381_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_c06bfb5befae7381_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_c06bfb5befae7381_00000000* tcd = (_0RL_cd_c06bfb5befae7381_00000000*)cd;
  p15::_impl_AAA* impl = (p15::_impl_AAA*) svnt->_ptrToInterface(p15::AAA::_PD_repoId);
  tcd->result = impl->f(tcd->arg_0);


}

::CORBA::Long p15::_objref_AAA::f(::CORBA::Long x)
{
  _0RL_cd_c06bfb5befae7381_00000000 _call_desc(_0RL_lcfn_c06bfb5befae7381_10000000, "f", 2);
  _call_desc.arg_0 = x;

  _invoke(_call_desc);
  return _call_desc.result;


}

p15::_pof_AAA::~_pof_AAA() {}


omniObjRef*
p15::_pof_AAA::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::p15::_objref_AAA(ior, id);
}


::CORBA::Boolean
p15::_pof_AAA::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::p15::AAA::_PD_repoId))
    return 1;
  
  return 0;
}

const p15::_pof_AAA _the_pof_p15_mAAA;

p15::_impl_AAA::~_impl_AAA() {}


::CORBA::Boolean
p15::_impl_AAA::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "f")) {

    _0RL_cd_c06bfb5befae7381_00000000 _call_desc(_0RL_lcfn_c06bfb5befae7381_10000000, "f", 2, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
p15::_impl_AAA::_ptrToInterface(const char* id)
{
  if (id == ::p15::AAA::_PD_repoId)
    return (::p15::_impl_AAA*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::p15::AAA::_PD_repoId))
    return (::p15::_impl_AAA*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
p15::_impl_AAA::_mostDerivedRepoId()
{
  return ::p15::AAA::_PD_repoId;
}

p15::BBB_ptr p15::BBB_Helper::_nil() {
  return ::p15::BBB::_nil();
}

::CORBA::Boolean p15::BBB_Helper::is_nil(::p15::BBB_ptr p) {
  return ::CORBA::is_nil(p);

}

void p15::BBB_Helper::release(::p15::BBB_ptr p) {
  ::CORBA::release(p);
}

void p15::BBB_Helper::marshalObjRef(::p15::BBB_ptr obj, cdrStream& s) {
  ::p15::BBB::_marshalObjRef(obj, s);
}

p15::BBB_ptr p15::BBB_Helper::unmarshalObjRef(cdrStream& s) {
  return ::p15::BBB::_unmarshalObjRef(s);
}

void p15::BBB_Helper::duplicate(::p15::BBB_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

p15::BBB_ptr
p15::BBB::_duplicate(::p15::BBB_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

p15::BBB_ptr
p15::BBB::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


p15::BBB_ptr
p15::BBB::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

p15::BBB_ptr
p15::BBB::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_BBB _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_BBB* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_BBB;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* p15::BBB::_PD_repoId = "IDL:p15/BBB:1.0";


p15::_objref_BBB::~_objref_BBB() {}



p15::_objref_BBB::_objref_BBB(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::p15::BBB::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
p15::_objref_BBB::_ptrToObjRef(const char* id)
{
  if (id == ::p15::BBB::_PD_repoId)
    return (::p15::BBB_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::p15::BBB::_PD_repoId))
    return (::p15::BBB_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for p15::BBB::getA

// Proxy call descriptor class. Mangled signature:
//  _cp15_mAAA
class _0RL_cd_c06bfb5befae7381_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_c06bfb5befae7381_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  p15::AAA_var result;
};

void _0RL_cd_c06bfb5befae7381_20000000::marshalReturnedValues(cdrStream& _n)
{
  p15::AAA::_marshalObjRef(result,_n);

}

void _0RL_cd_c06bfb5befae7381_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = p15::AAA::_unmarshalObjRef(_n);

}

const char* const _0RL_cd_c06bfb5befae7381_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_c06bfb5befae7381_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_c06bfb5befae7381_20000000* tcd = (_0RL_cd_c06bfb5befae7381_20000000*)cd;
  p15::_impl_BBB* impl = (p15::_impl_BBB*) svnt->_ptrToInterface(p15::BBB::_PD_repoId);
  tcd->result = impl->getA();


}

p15::AAA_ptr p15::_objref_BBB::getA()
{
  _0RL_cd_c06bfb5befae7381_20000000 _call_desc(_0RL_lcfn_c06bfb5befae7381_30000000, "getA", 5);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}

p15::_pof_BBB::~_pof_BBB() {}


omniObjRef*
p15::_pof_BBB::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::p15::_objref_BBB(ior, id);
}


::CORBA::Boolean
p15::_pof_BBB::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::p15::BBB::_PD_repoId))
    return 1;
  
  return 0;
}

const p15::_pof_BBB _the_pof_p15_mBBB;

p15::_impl_BBB::~_impl_BBB() {}


::CORBA::Boolean
p15::_impl_BBB::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "getA")) {

    _0RL_cd_c06bfb5befae7381_20000000 _call_desc(_0RL_lcfn_c06bfb5befae7381_30000000, "getA", 5, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
p15::_impl_BBB::_ptrToInterface(const char* id)
{
  if (id == ::p15::BBB::_PD_repoId)
    return (::p15::_impl_BBB*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::p15::BBB::_PD_repoId))
    return (::p15::_impl_BBB*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
p15::_impl_BBB::_mostDerivedRepoId()
{
  return ::p15::BBB::_PD_repoId;
}

POA_p15::AAA::~AAA() {}

POA_p15::BBB::~BBB() {}

